import { ClientReduxProvider } from "@/components/ClientReduxProvider";
import { Road_Rage, Roboto, Poppins } from "next/font/google";
import "./globals.css";

const roadRage = Road_Rage({
  weight: "400",
  variable: "--font-road-rage",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "300",
  variable: "--font-roboto",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: "300",
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ticket Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roadRage.variable} ${roboto.variable} ${poppins.variable} antialiased`}
      >
        <ClientReduxProvider>{children}</ClientReduxProvider>
      </body>
    </html>
  );
}
